modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"

[[mods]]
modId = "not_enough_vulkan"

version = "${version}"
displayName = "Not Enough Vulkan"

logoFile = "assets/not-enough-vulkan/textures/icon.png" #optional

authors = "FlashyReese, amiralimollaei"

description = '''
Features that shouldn't be in VulkanMod.
'''

[[dependencies.not_enough_vulkan]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.not_enough_vulkan]]
modId = "vulkanmod"
type = "required"
versionRange = "[0.6.9,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.not_enough_vulkan]]
modId = "greenlight"
type = "optional"
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "not-enough-vulkan.mixins.json"

[[accessTransformers]]
file="accesstransformer.cfg"
